# Generated by Django 5.2.8 on 2026-02-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dashboard', 'Dashboard General'), ('ventas', 'Reporte de Ventas'), ('analitica', 'Reporte Analítico'), ('recomendacion', 'Reporte de Recomendación')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='Snapshot del reporte generado')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Histórico',
                'verbose_name_plural': 'Reportes Históricos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
