# Generated by Django 5.2.8 on 2026-07-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidoitem_cantidad_carrito_carritoitem'),
        ('productos', '0002_producto_imagen_alter_producto_stock'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_producto_por_carrito'),
        ),
    ]
