# Generated by Django 5.2.8 on 2026-07-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_fecha'),
        ('productos', '0003_alter_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pedido_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='pedidos.pedidoitem'),
        ),
    ]
