# Generated by Django 5.2.8 on 2026-01-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMasMovida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_id', models.IntegerField()),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('total_movimiento', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría más movida',
                'verbose_name_plural': 'Categorías más movidas',
            },
        ),
        migrations.CreateModel(
            name='ProductoMasVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('total_vendido', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto más vendido',
                'verbose_name_plural': 'Productos más vendidos',
            },
        ),
        migrations.CreateModel(
            name='ReglaAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField()),
                ('soporte', models.FloatField()),
                ('confianza', models.FloatField()),
                ('lift', models.FloatField()),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regla de asociación',
                'verbose_name_plural': 'Reglas de asociación',
            },
        ),
        migrations.CreateModel(
            name='ClienteSegmentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente segmentado',
                'verbose_name_plural': 'Clientes segmentados',
            },
        ),
        migrations.CreateModel(
            name='IngresoPorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso por cliente',
                'verbose_name_plural': 'Ingresos por cliente',
            },
        ),
        migrations.DeleteModel(
            name='AnaliticaEvento',
        ),
    ]
