# Generated by Django 5.2.8 on 2026-01-31 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_categoriamasmovida_productomasvendido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriamasmovida',
            unique_together={('categoria_id', 'fecha_calculo')},
        ),
        migrations.AlterUniqueTogether(
            name='clientesegmentado',
            unique_together={('cliente', 'fecha_calculo')},
        ),
        migrations.AlterUniqueTogether(
            name='ingresoporcliente',
            unique_together={('cliente', 'fecha_calculo')},
        ),
        migrations.AddConstraint(
            model_name='productomasvendido',
            constraint=models.UniqueConstraint(fields=('producto_id', 'fecha_calculo'), name='unique_producto_por_dia'),
        ),
    ]
