# Generated by Django 5.2.8 on 2026-03-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0003_alter_categoriamasmovida_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngresoPorCliente',
        ),
    ]
